-- MySQL Script generated by MySQL Workbench
-- 10/29/16 01:01:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myshopping
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myshopping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myshopping` DEFAULT CHARACTER SET utf8 ;
USE `myshopping` ;

-- -----------------------------------------------------
-- Table `myshopping`.`usertypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`usertypes` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`usertypes` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`users` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`users` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `dashboardpassword` VARCHAR(255) NULL,
  `isEmailVerified` TINYINT(1) NULL DEFAULT 0,
  `usertype` INT(9) UNSIGNED NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `usertype_idx` (`usertype` ASC),
  CONSTRAINT `usertype-u`
    FOREIGN KEY (`usertype`)
    REFERENCES `myshopping`.`usertypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`usersmetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`usersmetas` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`usersmetas` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT(9) UNSIGNED NOT NULL,
  `metakey` VARCHAR(100) NULL,
  `metavalue` LONGTEXT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`categories` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`categories` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NOT NULL,
  `image` TEXT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `category_UNIQUE` (`category` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`productstatuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`productstatuses` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`productstatuses` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`products` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`products` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `purchaseprice` DOUBLE(9,5) NOT NULL,
  `saleprice` DOUBLE(9,5) NOT NULL,
  `discountpercent` DOUBLE(9,2) NULL,
  `images` LONGTEXT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `sku` VARCHAR(255) NOT NULL,
  `status` INT(9) UNSIGNED NOT NULL,
  `tax` DOUBLE(9,2) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC),
  UNIQUE INDEX `sku_UNIQUE` (`sku` ASC),
  INDEX `status_idx` (`status` ASC),
  CONSTRAINT `status-p`
    FOREIGN KEY (`status`)
    REFERENCES `myshopping`.`productstatuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`productcategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`productcategories` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`productcategories` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid` INT(9) UNSIGNED NOT NULL,
  `cid` INT(9) UNSIGNED NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `pid-pc`
    FOREIGN KEY (`id`)
    REFERENCES `myshopping`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cid-pc`
    FOREIGN KEY (`id`)
    REFERENCES `myshopping`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`productmetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`productmetas` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`productmetas` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid` INT(9) UNSIGNED NOT NULL,
  `metakey` VARCHAR(100) NULL,
  `metavalue` LONGTEXT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`creditcard_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`creditcard_details` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`creditcard_details` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cc_number` VARCHAR(19) NULL,
  `bankname` VARCHAR(155) NULL,
  `bankaccountnumber` VARCHAR(100) NULL,
  `cvv` VARCHAR(4) NULL,
  `cc_expiry` DATE NULL,
  `name_on_cc` VARCHAR(155) NULL,
  `pin` VARCHAR(100) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`orderstatuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`orderstatuses` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`orderstatuses` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`orders` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`orders` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `givenBy_uid` INT(9) UNSIGNED NULL,
  `invoiceNumber` VARCHAR(100) NULL,
  `invoicepath` LONGTEXT NULL,
  `cc_details` INT(9) UNSIGNED NULL,
  `status` INT(9) UNSIGNED NULL,
  `totalAmount` INT(9) UNSIGNED NULL,
  `salesTax` DOUBLE(9,2) NULL,
  `finalAmount` DOUBLE(9,2) UNSIGNED NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `invoiceNumber_UNIQUE` (`invoiceNumber` ASC),
  INDEX `ordergiven_By_idx` (`givenBy_uid` ASC),
  INDEX `cc_details_idx` (`cc_details` ASC),
  INDEX `order_status_idx` (`status` ASC),
  CONSTRAINT `ordergiven_By-o`
    FOREIGN KEY (`givenBy_uid`)
    REFERENCES `myshopping`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cc_details-o`
    FOREIGN KEY (`cc_details`)
    REFERENCES `myshopping`.`creditcard_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_status-o`
    FOREIGN KEY (`status`)
    REFERENCES `myshopping`.`orderstatuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`orderdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`orderdetails` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`orderdetails` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `oid` INT(9) UNSIGNED NULL,
  `pid` INT(9) UNSIGNED NULL,
  `quantity` INT(9) UNSIGNED NULL,
  `bill` DOUBLE(9,2) NULL,
  `discountpercent` DOUBLE(9,2) NULL,
  `payableamount` DOUBLE(9,2) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `oid_idx` (`oid` ASC),
  CONSTRAINT `oid-od`
    FOREIGN KEY (`oid`)
    REFERENCES `myshopping`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`ordermetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`ordermetas` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`ordermetas` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `oid` INT(9) UNSIGNED NULL,
  `metakey` VARCHAR(100) NULL,
  `metavalue` LONGTEXT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`settings` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`settings` (
  `id` INT(9) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(155) NULL,
  `value` LONGTEXT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myshopping`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myshopping`.`countries` ;

CREATE TABLE IF NOT EXISTS `myshopping`.`countries` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `countryname` VARCHAR(100) NOT NULL,
  `countryshortname` VARCHAR(50) NOT NULL,
  `currencyFullName` VARCHAR(100) NOT NULL,
  `currenctyShort` VARCHAR(50) NOT NULL,
  `countryflagimage` TEXT NULL,
  `currencysymbol` VARCHAR(50) NULL,
  `isActive` TINYINT NULL DEFAULT 0,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `countryname_UNIQUE` (`countryname` ASC),
  UNIQUE INDEX `countryshortname_UNIQUE` (`countryshortname` ASC),
  UNIQUE INDEX `currenctyShort_UNIQUE` (`currenctyShort` ASC),
  UNIQUE INDEX `currencyFullName_UNIQUE` (`currencyFullName` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
